<a href="https://colab.research.google.com/github/WagnerLopesCardozo/Projetos-de-Estudo-CD-FaTec-Ourinhos/blob/main/Opera%C3%A7%C3%B5es_Matrizes_Biblioteca_NUMPY_%C3%81lgebra_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Operações com Matrizes Usando a Biblioteca NumPy - Álgebra Linear

In [2]:
import numpy as np

In [3]:
A = np.array([[9, 7, 49], [1, 5, 7], [72, 4, 3]]) #criando a matriz

In [4]:
A #mostrando a matriz

array([[ 9,  7, 49],
       [ 1,  5,  7],
       [72,  4,  3]])

In [5]:
print(A) #mostrando a matriz

[[ 9  7 49]
 [ 1  5  7]
 [72  4  3]]


In [6]:
A.shape #mostrando ordem da matriz

(3, 3)

In [8]:
A = np.array([[9, 7, 49], [1, 5, 7], [72, 4, 3]], dtype = float) #definindo como números decimais

In [9]:
A

array([[ 9.,  7., 49.],
       [ 1.,  5.,  7.],
       [72.,  4.,  3.]])

In [10]:
print(A)

[[ 9.  7. 49.]
 [ 1.  5.  7.]
 [72.  4.  3.]]


In [11]:
A = np.array([[9, 7, 49], [1, 5, 7], [72, 4, 3]], dtype = complex)

In [12]:
A

array([[ 9.+0.j,  7.+0.j, 49.+0.j],
       [ 1.+0.j,  5.+0.j,  7.+0.j],
       [72.+0.j,  4.+0.j,  3.+0.j]])

In [13]:
print(A)

[[ 9.+0.j  7.+0.j 49.+0.j]
 [ 1.+0.j  5.+0.j  7.+0.j]
 [72.+0.j  4.+0.j  3.+0.j]]


In [14]:
A = np.random.rand(3, 3) #gerando uma matriz aleatória

In [16]:
A

array([[0.18602199, 0.99570726, 0.51667036],
       [0.07130001, 0.76451808, 0.32577674],
       [0.79179148, 0.06597493, 0.44551755]])

In [18]:
np.zeros((3, 4)) #gerando uma matriz nula

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3, 4)) #gerando matriz unitária

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.ones((3, 4))*7 #gerando matriz unitária com mesmo número

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [21]:
from numpy.core.fromnumeric import reshape
A = np.arange (12).reshape(6, 2) #outra forma de declarar uma matriz com o comando RESHAPE

In [22]:
A

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
np.diag([1, 2, 3, 4, 5, 6, 7]) #declarando uma matriz escolhnedo a diagonal principal

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [24]:
np.identity(5) #declarando uma matriz identidade

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
A

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [27]:
A[3, 1] #recuperando um determinado elemento da matriz

7

In [28]:
A[:, 1] #recuperando elementos de uma determinada coluna

array([ 1,  3,  5,  7,  9, 11])

In [29]:
A[3, :] #recuperando elementos de uma determinada linha

array([6, 7])

In [46]:
Xinv = np.array([[2, 3], [4, 5]]) #declarando uma matriz para operações

In [47]:
Xinv

array([[2, 3],
       [4, 5]])

In [48]:
Xinv = np.linalg.inv(Xinv) #calculando a inversa da matriz 
                           #linalg é um subpacote dentro do NUMPY para cálculo de inver. e determinantes (linalg - linear álgebra)

In [49]:
Xinv

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [53]:
Xdet = np.array([[2, 3], [4, 5]])

In [54]:
Xdet

array([[2, 3],
       [4, 5]])

In [55]:
Xdet = np.linalg.det(Xdet) #calculando o determinante da matriz

In [56]:
Xdet

-2.0

In [57]:
Xt = np.array([[2, 3], [4, 5]])

In [58]:
Xt

array([[2, 3],
       [4, 5]])

In [60]:
Xt = np.transpose(Xt) #mostrando a matriz transposta

In [61]:
Xt


array([[2, 4],
       [3, 5]])

In [63]:
Y = np.array([[2, 3, 4], [5, 6, 7]]) #declarando nova matriz

In [64]:
Y

array([[2, 3, 4],
       [5, 6, 7]])

In [73]:
Z = np.array([[1, 2, 3], [4, 5, 6]]) #declarando nova matriz

In [74]:
Z

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
Y + Z

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [76]:
Y - Z

array([[1, 1, 1],
       [1, 1, 1]])

In [77]:
M = np.array([[2, 3, 4], [5, 6, 7]]) #declarando novas matrizes

In [78]:
M

array([[2, 3, 4],
       [5, 6, 7]])

In [79]:
N = np.array([[2, 3], [4, 5], [6, 7]]) #declarando novas matrizes

In [80]:
N


array([[2, 3],
       [4, 5],
       [6, 7]])

In [81]:
np.dot(M, N) #multiplicando matrizes

array([[40, 49],
       [76, 94]])

In [9]:
W = np.array([[2, 3], [5, 6]])

In [10]:
W

array([[2, 3],
       [5, 6]])

In [11]:
U = np.array([[8, 9], [11, 12]])

In [12]:
U

array([[ 8,  9],
       [11, 12]])

W / U = W * U -¹

In [13]:
np.dot(W, np.linalg.inv(U)) #divisão de matrizes

array([[ 3., -2.],
       [ 2., -1.]])

In [14]:
S = np.array([[3, 4, 5], [7, 8, 9]])

In [15]:
S

array([[3, 4, 5],
       [7, 8, 9]])

In [16]:
F = np.array([[12, 23, 34], [45, 56, 67]])

In [17]:
F

array([[12, 23, 34],
       [45, 56, 67]])

In [18]:
H = np.array([[89, 78, 67], [56, 45, 34]])

In [19]:
H

array([[89, 78, 67],
       [56, 45, 34]])

In [20]:
K = S + F * H #operação de soma e multiplicação de matrizes

In [21]:
K

array([[1071, 1798, 2283],
       [2527, 2528, 2287]])